config/routes.rb
Rails.application.routes.draw do
  # get 'users/new'

  devise_for :users

  resources :books

  resources :users

  root to: 'homes#index'

  get 'home/about',to: 'homes#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2 ,maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
  end

  def new
  	@book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have creatad user successfully."
       redirect_to user_path(current_user)
    #current_userでサインインしているユーザーを取得する
    else
       render action: :edit
    end
  end


  def edit
  	@user = User.find(params[:id])
    if current_user.id != @user.id
       redirect_to user_path(current_user.id)
    end
  end

  def create
    @users = User.all
    # ストロングパラメーターを使用
    @book = Book.new(book_params)
    if @book.save
       flash[:notice] = "You have creatad book successfully."
       redirect_to book_path
    end
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end


  private

  def user_params
  	params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-3">


<h2>User info</h2>

 <div>
  <%= attachment_image_tag user, :profile_image, size:"100x100", format: 'jpeg',fallback: "no_image.jpg" %>
 </div>


 <table class="table">
    <tbody>
        <tr></tr>
        <tr>
            <th>name</th>
            <th><%= user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
        </tr>
    </tbody>
</table>


<div class="row">
<%= link_to "", edit_user_path(user.id),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
</div>


<h2>New book</h2>
<!-- form_for部分 -->
<%= form_for(books) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book',class: "btn btn-primary col-xs-12" %>

<% end %>

</div>

app/views/users/edit.html.erb
  <% if @user.errors.any? %>
     <h2><%= @user.errors.count %> errors prohibited this book from being saved:</h2>

    <ul>

      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

    </ul>

  <% end %>

<h2>User info</h2>

<%= form_for(@user) do |f| %>

    <h4>Name</h4>
    <%= f.text_field :name %>

    <h4>Image</h4>
    <%= f.attachment_field :profile_image %>

    <h4>Introduction</h4>
    <%= f.text_area :introduction %>


    <h4></h4>
    <%= f.submit 'Update User',class: "btn btn-primary" %>

<% end %>

app/views/users/index.html.erb
<%= render partial: 'users/list.html', locals: {user:current_user ,books:@book} %>


<div class="col-xs-9">
<h1>Users</h1>

<table>
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
        </tr>
    </thead>

    <tbody>
    	<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, size: '40x40', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %></td>
			<td><%= user.name %></td>

			<td><%= link_to "Show",  user_path(user.id) %></td>
		</tr>
    <% end %>

    </tbody>
</table>

</div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-3">


<h2>User info</h2>

 <div>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
 </div>


 <table>
    <tbody>
        <tr></tr>
        <tr>
            <th>name</th>
            <th><%= @user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
        </tr>
    </tbody>
</table>


<div class="row">
<%= link_to "", edit_user_path(@user.id),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
</div>


<h2>New book</h2>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book',class: "btn btn-primary col-xs-12" %>

<% end %>

   <% if @book.errors.any? %>
     <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
    <% end %>

</div>

<div class="col-xs-9">
<h1>Books</h1>

<table class="table table-hover table-inverse">
    <thead>
        <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
        </tr>
    </thead>

    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td> <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%></td>

            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>

        </tr>
        <% end %>
    </tbody>
</table>

</div>
</div>