config/routes.rb
Rails.application.routes.draw do
  # get 'users/new'

  devise_for :users

  resources :books

  resources :users

  root to: 'homes#index'

  get 'home/about',to: 'homes#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true, length: { maximum: 50 }
	validates :body, presence: true, length: { maximum: 140 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!

	def new #新たに投稿するためのページを呼ぶアクション
		@book = Book.new
	end

   # 投稿データの保存
	def create
		@book = Book.new(book_params)

		@book.user_id = current_user.id

		if @book.save
		    flash[:notice] = "You have creatad book successfully."

		    redirect_to book_path(@book.id)

		else
			@user = current_user
			@books = Book.all
			render action: :index
		end
	end

	def update
		@book = Book.find(params[:id])

		if @book.update(book_params)
			flash[:notice] = "You have updated book successfully."

			redirect_to book_path(@book.id)

        else
        	render action: :edit
        end
  end

	def index

		@book = Book.new#form(新たに作る為の入力欄・空箱)
		@books = Book.all #booksと複数形にした方が自然

		@user = current_user
	end

	def show
		@book = Book.find(params[:id])
		@user = @book.user#ブックを投稿したユーザ
	end

	def edit
		@book = Book.find(params[:id])
		if current_user.id != @book.user_id
			redirect_to books_path
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path, notice:"successfully."
	end

	# 投稿データのストロングパラメータ
	private
    def book_params
        params.require(:book).permit(:title, :body)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
    <div class="row">

<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>

<% if @book.errors.any? %>
     <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>

    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
<% end %>


<h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

  <div class="row">
    <%= f.submit 'Update Book',class: "btn btn-primary" %>
  </div>
<% end %>

  <div class="row">
    <%= link_to "Show",book_path(@book.id) %>
   |
   <%= link_to "Back", books_path %>
  </div>

  </div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
     <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
    <% end %>

<%= render partial: 'users/list.html', locals: {user:@user ,books:@book} %>



<div class="col-xs-9">
<h2>Books</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
        </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
    <tr>
      <td><%= link_to attachment_image_tag(book.user, :profile_image, size: '40x40', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"),user_path(book.id) %></td>

      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>


    </tr>
    <% end %>
    </tbody>
</table>

</div>
</div>

app/views/books/show.html.erb
<%= render partial: 'users/list.html', locals: {user: @book.user,books: Book.new} %>

<div class="col-xs-9">

<h2>Book detail</h2>

<table class="table">
    <tbody>
        <tr>
            <td> <%= attachment_image_tag @user, :profile_image, size: '40x40', fallback:"no_image.jpg",size:'40x40' %></td>


            <td><%= @book.title %></td>

            <td><%= @book.body %></td>

		<% if @user==current_user %>
            <td><%= link_to "Edit", edit_book_path(@book.id) %></td>

            <td><%=link_to 'Destroy', book_path(@book.id), method: :delete,  "data-confirm" => "本当に消しますか？"%></td>
        <% end %>

        </tr>
    </tbody>
</table>

 <%= link_to @user.name, user_path(@book.user) %>

</div>