config/routes.rb
Rails.application.routes.draw do
  # get 'users/new'

  devise_for :users

  resources :books

  resources :users

  root to: 'homes#index'

  get 'home/about',to: 'homes#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid navbar navbar-inverse">

    <nav class="nav navbar-nav navbar-left">
       <h2 style="color:white;">Bookers</h2>
    </nav>

    <nav>

       <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">

             <% if user_signed_in? %>

              <li class="">
              </li>

              <li class="">
               <%= link_to 'Home', user_path(current_user.id), class:'glyphicon glyphicon-home' %>
              </li>

              <li class="">
                <%= link_to 'Users', users_path, class:'glyphicon glyphicon-user'%>
              </li>

              <li class="">
                <%= link_to 'Books', books_path, class:'glyphicon glyphicon-book'%>
              </li>

              <li class="">
                <%= link_to "logout", destroy_user_session_path, method: :delete, class:'glyphicon glyphicon-log-out' %>
              </li>

             <% else %>

              <li class="">
                <%= link_to "Home", root_path, class:'glyphicon glyphicon-home'%>
              </li>

              <li class="">
                <%= link_to "About", home_about_path, class:'glyphicon glyphicon-link about' %>
              </li>

              <li class="">
                <%= link_to "sign up", new_user_registration_path, class:'glyphicon glyphicon-edit sign_up' %>
              </li>
              <li class="">
                <%= link_to "login", new_user_session_path, class:'glyphicon glyphicon-log-in sign_in' %>
              </li>
             <% end %>
             </li>
         </ul>
        </nav>
      </div>

   <% if flash[:notice] %>
   　 <p><%= flash[:notice] %></p>
  　<% end %>

    <%= yield %>

    <div class="col-xs-3 col-xs-offset-9">
     <p>CopyRight Infratop.inc</p>
    </div>

      </div>
  </body>
</html>